/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainAndGUI;

import java.io.IOException;
import java.util.InputMismatchException;
import javax.swing.DefaultComboBoxModel;
import SysClasses.AllExercisesSys;
import SysClasses.ExerciseSys;
import Inheritance.WorkoutProgram;

/**
 *
 * @author Talha
 */
public class WorkoutProgramFrame extends javax.swing.JFrame {

    MainExercisesFrame esf;

    /**
     * Creates new form WorkoutProgramForm
     */
    public WorkoutProgramFrame(MainExercisesFrame i) {
        initComponents();
        esf = i;

    }

    private WorkoutProgramFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectExerciseCb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        programOutputTA = new javax.swing.JTextArea();
        dispBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        weightsTextField = new javax.swing.JTextField();
        repsTextField = new javax.swing.JTextField();
        setsTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        removeCB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Workout Program");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        selectExerciseCb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectExerciseCbMouseClicked(evt);
            }
        });
        selectExerciseCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectExerciseCbActionPerformed(evt);
            }
        });

        programOutputTA.setColumns(20);
        programOutputTA.setRows(5);
        jScrollPane1.setViewportView(programOutputTA);

        dispBtn.setText("Display Program");
        dispBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Add Exercise");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove Exercise");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Weights Lifted(kgs):");

        jLabel3.setText("Reps:");

        jLabel4.setText("Sets:");

        jLabel1.setText("Select Exercise to add:");

        removeCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeCBMouseClicked(evt);
            }
        });
        removeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCBActionPerformed(evt);
            }
        });

        jLabel5.setText("Select Exercise to remove:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(weightsTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(setsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(repsTextField))
                                        .addComponent(jLabel1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(selectExerciseCb, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dispBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(removeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(weightsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(repsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(setsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectExerciseCb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(dispBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        boolean status = true;
        try {
            try {
                if (selectExerciseCb.getSelectedItem() == null) {
                    programOutputTA.setText("Select an Exercise");
                    status = false;
                }
                if (setsTextField.getSelectedText().isEmpty()) {
                    programOutputTA.setText("Enter number of sets you did recently");
                    status = false;
                }
                if (repsTextField.getSelectedText().isEmpty()) {
                    programOutputTA.setText("Enter the number of reps you did recently");
                    status = false;
                }
            } catch (NullPointerException ex) {
            }
            if (status) {
                String s;
                s = (String) selectExerciseCb.getSelectedItem();
                WorkoutProgram w = AllExercisesSys.searchExercise(s);
                String exerciseId = w.getExerciseId();
                int noOfReps = Integer.parseInt(repsTextField.getText());
                int noOfSets = Integer.parseInt(setsTextField.getText());
                int weightsLifted = Integer.parseInt(weightsTextField.getText());
                boolean stts = ExerciseSys.addExercise(exerciseId, weightsLifted, noOfSets, noOfReps);
                if (!stts) {
                    programOutputTA.setText("Exercise already exists in the program!");
                } else {
                    programOutputTA.setText("Exercise Added!\n" + ExerciseSys.getAllSelectedExercises());
                }
                repsTextField.setText("");
                setsTextField.setText("");
                weightsTextField.setText("");
            }
        } catch (NumberFormatException ex) {
            programOutputTA.setText("Either any empty fields or some fields have dont have an integer value");
        }

    }//GEN-LAST:event_addBtnActionPerformed

    @SuppressWarnings("unchecked")
    private void selectExerciseCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectExerciseCbActionPerformed

    }//GEN-LAST:event_selectExerciseCbActionPerformed

    private void selectExerciseCbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectExerciseCbMouseClicked
        if (selectExerciseCb.getItemCount() == 0) {
            String[] exNames = AllExercisesSys.getAllExercisesNames();
            for (int i = 0; i < exNames.length; i++) {
                selectExerciseCb.addItem(exNames[i]);
            }
        }
    }//GEN-LAST:event_selectExerciseCbMouseClicked

    private void dispBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispBtnActionPerformed
        if (ExerciseSys.SelectedExList.isEmpty()) {
            programOutputTA.setText("You have not added any exercises to your your Workout Program!");
        } else {
            programOutputTA.setText("List of all your selected exercises with details and strength Plan for next week:\n\n" + ExerciseSys.getAllSelectedExercises());
        }

    }//GEN-LAST:event_dispBtnActionPerformed

    private void removeCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCBMouseClicked
        if (removeCB.getSelectedItem() == null) {
            String[] exNames = ExerciseSys.getAllExercisesNames();
            for (int i = 0; i < exNames.length; i++) {
                removeCB.addItem(exNames[i]);
            }
        }
    }//GEN-LAST:event_removeCBMouseClicked

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        try {
            String s;
            s = (String) selectExerciseCb.getSelectedItem();
            WorkoutProgram w = AllExercisesSys.searchExercise(s);
            WorkoutProgram sm = ExerciseSys.removeExercise(w.getExerciseId());
            programOutputTA.setText(sm.getExerciseName() + " is removed from your program");
        } catch (NullPointerException ex) {
            programOutputTA.setText("No Exercise added to the program!");
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void removeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkoutProgramFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkoutProgramFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkoutProgramFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkoutProgramFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("unchecked")
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton dispBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea programOutputTA;
    private javax.swing.JButton removeBtn;
    private javax.swing.JComboBox<String> removeCB;
    private javax.swing.JTextField repsTextField;
    private javax.swing.JComboBox<String> selectExerciseCb;
    private javax.swing.JTextField setsTextField;
    private javax.swing.JTextField weightsTextField;
    // End of variables declaration//GEN-END:variables
}
